"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "ru" | "ar";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navbar & Common
    home: "Home",
    explore: "Explore",
    myTrips: "My Trips",
    bookNow: "Book Now",
    aboutUs: "About Us",
    contact: "Contact",
    welcome: "Welcome to Sunrise Tours",
    makingEveryMoment: "MAKING EVERY MOMENT UNFORGETTABLE",

    // Home Page
    discoveryAwaits: "Discovery Awaits",
    exclusive: "Exclusive",
    experiences: "Experiences",
    heroDesc: "Discover the hidden gems of Sharm El-Shaikh and Dahab with our curated daily excursions, designed for the modern traveler.",
    all: "All",
    daily: "Daily",
    safari: "Safari",
    seaTrips: "Sea Trips",
    priceText: "Price",
    reviews: "Reviews",

    // About Page
    ourStory: "Our Story & Vision",
    whoWeAre: "Who We Are",
    passionateExperts: "Passionate Experts",
    tailoredExperience: "Tailored Experience",
    safetyComfort: "Safety & Comfort",
    localPresence: "Local Presence",
    happyTravelers: "Happy Travelers",
    safetyRating: "Safety Rating",
    egypt: "Egypt",
    discoverPassion: "Discover the passion behind Sharm El-Sheikh's premier excursion provider.",
    whoWeAreDesc: "At Sunrise Tours, we believe travel has the power to transform lives. Since our inception, we've dedicated ourselves to providing authentic, safe, and luxurious desert and sea experiences that showcase the true beauty of Egypt's Red Sea coast.",
    expertsDesc: "Our team is made up of avid travelers who know every hidden gem in the Sinai.",
    tailoredDesc: "We provide customized journeys designed to fit your unique travel style and needs.",
    safetyDesc: "Your safety and comfort are our top priorities for every single expedition.",
    localDesc: "Being locals gives us the edge in providing authentic experiences you won't find anywhere else.",
    masterpiece: "Embark on a journey of discovery where every journey is a masterpiece.",

    // Trips Page
    myAdventures: "My Adventures",
    manageBookings: "Manage your bookings and relive your favorite moments.",
    appointments: "Appointments",
    history: "History",
    wishlist: "Wishlist",
    viewDetails: "View Details",
    planNewAdventure: "Plan New Adventure",
    explorePremium: "Explore 24+ premium excursions",

    // Footer
    footerDesc: "Redefining luxury travel in Sharm El-Sheikh. We curate unforgettable experiences that blend adventure, comfort, and local heritage.",
    navigation: "Navigation",
    exploreTours: "Explore Tours",
    myBookings: "My Bookings",
    support: "Support",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    refundPolicy: "Refund Policy",
    contactSupport: "Contact Support",
    connect: "Connect",
    sharmLocation: "Sharm El-Sheikh",
    sinaiEgypt: "South Sinai, Egypt",
    supportAvailable: "24/7 Support Available",
    allRightsReserved: "ALL RIGHTS RESERVED.",

    // Tour Detail Page
    tourNotFound: "Tour Not Found",
    tourNotFoundDesc: "The adventure you're looking for might have been moved or is currently being updated with new premium features.",
    returnToAll: "Return to All Tours",
    experienceOverview: "Experience Overview",
    tripItinerary: "Trip Itinerary",
    whatsIncluded: "What's Included",
    notIncluded: "Not Included",
    essentialPacking: "Essential Packing",
    importantNotes: "Important Notes",
    priceStartingFrom: "Price Starting From",
    adults: "Adults",
    child: "Child (5-11y)",
    under5: "Under 5 Years",
    bookThisExperience: "Book This Experience",
    secureCheckout: "Secure checkout • Instant Confirmation",
    needAssistance: "Need Assistance?",
    supportTeamDesc: "Our travel experts are available 24/7 to help with your booking.",

    // Categories & Locations
    dailytour: "Daily Tour",
    yachttrip: "Yacht Trip",
    adventure: "Adventure",
    fullday: "Full Day",
    evening: "Evening",
    diving: "Diving",
    nationalpark: "National Park",
    watersports: "Water Sports",
    seatrip: "Sea Trip",
    historical: "Historical",
    religious: "Religious",
    sightseeing: "Sightseeing",
    airtour: "Air Tour",
    entertainment: "Entertainment",
    family: "Family",
    wellness: "Wellness",
    international: "International",
    interactive: "Interactive",
    
    sharmelshaikhislands: "Sharm El Sheikh Islands",
    desertparksharm: "Desert Park, Sharm",
    dahabbluehole: "Dahab & Blue Hole",
    sharmmarinaport: "Sharm Marina Port",
    naambaymarinearea: "Naama Bay Marine Area",
    southsinaireserve: "South Sinai Reserve",
    coralreefsanctuary: "Coral Reef Sanctuary",
    sharmelshaikh: "Sharm El Sheikh",
    sinai: "Sinai",
    sharm: "Sharm",
    dahab: "Dahab",
    redsea: "Red Sea",
    reserve: "National Reserve",
    cairo: "Cairo",
    nuiba: "Nuiba",
    jordan: "Jordan",

    // Common Items
    hoteltransfer: "Hotel Transfer",
    lunchonyacht: "Lunch on Yacht",
    softdrinks: "Soft Drinks",
    professionalguide: "Professional Guide",
    snorkelinggear: "Snorkeling Gear",
    divinggear: "Diving Gear",
    personalexpenses: "Personal Expenses",
    passport: "Passport",
    swimwear: "Swimwear",
    towel: "Towel",
    sunscreen: "Sunscreen",
    bedouintea: "Bedouin Tea",
    quadbike: "Quad Bike",
    camelride: "Camel Ride",

    // Durations
    "9hours": "9 Hours",
    "2.5hours": "2.5 Hours",
    "1.5hours": "1.5 Hours",
    "6hours": "6 Hours",
    "2hours": "2 Hours",
    "5hours": "5 Hours",
    "24hours": "24 Hours",
    "17hours": "17 Hours",
    "11hours": "11 Hours",
    "10hours": "10 Hours",
    "7hours": "7 Hours",
    "4hours": "4 Hours",
    "3hours": "3 Hours",

    // Common Tour Titles
    rasmohammedyachtexperience: "Ras Mohammed Yacht Experience",
    quadbikesafariicamelride: "Quad Bike Safari & Camel Ride",
    superdahabdiscovery5in1: "Super Dahab Discovery 5-in-1",
    vippirateshipeveningcruise: "VIP Pirate Ship Evening Cruise",
    shoredivingadventure: "Shore Diving Adventure",
    rasmohammednationalpark: "Ras Mohammed National Park",
    divingifunexperience: "Diving & Fun Experience",
    tiranislandyachtexcursion: "Tiran Island Yacht Excursion",
    cairoipyramidsdiscovery: "Cairo & Pyramids Discovery",
    mountmosesistcatherine: "Mount Moses & St. Catherine",
    bathyscaphesubmarineview: "Bathyscaphe Submarine View",
    stcatherinesmonastery: "St. Catherine's Monastery",
    coloredcanyonsalama5in1: "Colored Canyon Salama 5-in-1",
    buggysafariicameltrek: "Buggy Safari & Camel Trek",
    dahabdiscoveryspecial: "Dahab Discovery Special",
    cairoipyramidsbyplane: "Cairo & Pyramids by Plane",
    supersafaridinnerishow: "Super Safari Dinner & Show",
    albatroswaterparkday: "Albatross Waterpark Day",
    luxorancientruinstrip: "Luxor Ancient Ruins Trip",
    parasailinghighexperience: "Parasailing High Experience",
    petratreasuryjordan: "Petra Treasury - Jordan",
    turkishbathimassage: "Turkish Bath & Massage",
    dolphinariumfunshow: "Dolphinarium Fun Show",
    swimmingwithdolphins: "Swimming with Dolphins",
  },
  ru: {
    home: "Главная",
    explore: "Экскурсии",
    myTrips: "Мои поездки",
    bookNow: "Забронировать",
    aboutUs: "О компании",
    contact: "Контакты",
    welcome: "Добро пожаловать в Sunrise Tours",
    makingEveryMoment: "МЫ СОЗДАЕМ НЕЗАБЫВАЕМЫЕ МОМЕНТЫ",

    discoveryAwaits: "Откройте для себя Египет",
    exclusive: "Эксклюзивные",
    experiences: "Впечатления",
    heroDesc: "Откройте для себя скрытые жемчужины Шарм-эш-Шейха и Дахаба с нашими тщательно отобранными авторскими экскурсиями.",
    all: "Все",
    daily: "Ежедневные",
    safari: "Сафари",
    seaTrips: "Морские прогулки",
    priceText: "Стоимость",
    reviews: "Отзывы",

    ourStory: "Наша история и видение",
    whoWeAre: "О нас",
    passionateExperts: "Влюбленные в свое дело эксперты",
    tailoredExperience: "Индивидуальный подход",
    safetyComfort: "Безопасность и комфорт",
    localPresence: "Знание региона",
    happyTravelers: "Довольных туристов",
    safetyRating: "Рейтинг безопасности",
    egypt: "Египет",
    discoverPassion: "Откройте для себя лучшее туристическое агентство Шарм-эш-Шейха.",
    whoWeAreDesc: "В Sunrise Tours мы верим, что путешествия способны менять жизнь. С самого основания мы посвятили себя созданию аутентичных, безопасных и роскошных туров по пустыне и морю.",
    expertsDesc: "Наша команда — это заядлые путешественники, знающие каждый потаенный уголок Синая.",
    tailoredDesc: "Мы предлагаем персонализированные маршруты, адаптированные под ваши вкусы и пожелания.",
    safetyDesc: "Ваша безопасность и непревзойденный комфорт — наши главные приоритеты.",
    localDesc: "Идеальное знание региона позволяет нам предлагать уникальные маршруты, которых вы не найдете у других.",
    masterpiece: "Отправьтесь в путешествие, где каждая поездка — настоящее произведение искусства.",

    myAdventures: "Мои путешествия",
    manageBookings: "Управляйте бронированиями и вспоминайте лучшие моменты.",
    appointments: "Бронирования",
    history: "История",
    wishlist: "Избранное",
    viewDetails: "Подробнее",
    planNewAdventure: "Новое приключение",
    explorePremium: "Более 24 премиальных экскурсий",

    footerDesc: "Новый взгляд на роскошные путешествия в Шарм-эш-Шейхе. Мы создаем незабываемые впечатления, сочетая приключения, комфорт и местный колорит.",
    navigation: "Меню",
    exploreTours: "Каталог туров",
    myBookings: "Мои бронирования",
    support: "Помощь",
    privacyPolicy: "Политика конфиденциальности",
    termsOfService: "Пользовательское соглашение",
    refundPolicy: "Условия возврата",
    contactSupport: "Служба поддержки",
    connect: "Связь с нами",
    sharmLocation: "Шарм-эш-Шейх",
    sinaiEgypt: "Южный Синай, Египет",
    supportAvailable: "Поддержка 24/7",
    allRightsReserved: "ВСЕ ПРАВА ЗАЩИЩЕНЫ.",

    tourNotFound: "Тур не найден",
    tourNotFoundDesc: "Возможно, данная экскурсия была перемещена или мы обновляем информацию о ней.",
    returnToAll: "Вернуться ко всем турам",
    experienceOverview: "Описание экскурсии",
    tripItinerary: "Программа поездки",
    whatsIncluded: "Что включено",
    notIncluded: "Не включено",
    essentialPacking: "Что взять с собой",
    importantNotes: "Важные примечания",
    priceStartingFrom: "Стоимость от",
    adults: "Взрослые",
    child: "Дети (5-11 лет)",
    under5: "До 5 лет",
    bookThisExperience: "Забронировать экскурсию",
    secureCheckout: "Безопасное бронирование • Мгновенное подтверждение",
    needAssistance: "Нужна помощь?",
    supportTeamDesc: "Наши специалисты готовы помочь вам с бронированием 24/7.",

    dailytour: "Ежедневный тур",
    yachttrip: "Морская прогулка",
    adventure: "Приключение",
    fullday: "На весь день",
    evening: "Вечерний тур",
    diving: "Дайвинг",
    nationalpark: "Национальный парк",
    watersports: "Водный спорт",
    seatrip: "Морская экскурсия",
    historical: "Исторический тур",
    religious: "Паломничество",
    sightseeing: "Обзорная экскурсия",
    airtour: "Авиатур",
    entertainment: "Развлечения",
    family: "Для всей семьи",
    wellness: "Спа и релакс",
    international: "Зарубежный тур",
    interactive: "Интерактивный тур",
    
    sharmelshaikhislands: "Острова Шарм-эш-Шейха",
    desertparksharm: "Пустыня Шарм-эш-Шейха",
    dahabbluehole: "Дахаб и Блу-Хоул",
    sharmmarinaport: "Порт Марина, Шарм",
    naambaymarinearea: "Бухта Наама-Бей",
    southsinaireserve: "Заповедник Южного Синая",
    coralreefsanctuary: "Коралловый заповедник",
    sharmelshaikh: "Шарм-эш-Шейх",
    sinai: "Синай",
    sharm: "Шарм",
    dahab: "Дахаб",
    redsea: "Красное море",
    reserve: "Заповедник",
    cairo: "Каир",
    nuiba: "Нувейба",
    jordan: "Иордания",

    hoteltransfer: "Трансфер туда и обратно",
    lunchonyacht: "Обед на яхте",
    softdrinks: "Безалкогольные напитки",
    professionalguide: "Профессиональный гид",
    snorkelinggear: "Маска и ласты",
    divinggear: "Снаряжение для дайвинга",
    personalexpenses: "Личные расходы",
    passport: "Паспорт",
    swimwear: "Купальник / Плавки",
    towel: "Полотенце",
    sunscreen: "Солнцезащитный крем",
    bedouintea: "Бедуинский чай",
    quadbike: "Квадроциклы",
    camelride: "Катание на верблюдах",

    "9hours": "9 часов",
    "2.5hours": "2.5 часа",
    "1.5hours": "1.5 часа",
    "6hours": "6 часов",
    "2hours": "2 часа",
    "5hours": "5 часов",
    "24hours": "24 часа",
    "17hours": "17 часов",
    "11hours": "11 часов",
    "10hours": "10 часов",
    "7hours": "7 часов",
    "4hours": "4 часа",
    "3hours": "3 часа",

    rasmohammedyachtexperience: "На яхте в Рас-Мохаммед",
    quadbikesafariicamelride: "Сафари на квадроциклах и верблюды",
    superdahabdiscovery5in1: "Супер Дахаб 5 в 1",
    vippirateshipeveningcruise: "Круиз на Пиратской яхте (VIP)",
    shoredivingadventure: "Дайвинг с берега",
    rasmohammednationalpark: "Национальный парк Рас-Мохаммед",
    divingifunexperience: "Дайвинг и водный спорт",
    tiranislandyachtexcursion: "Круиз к острову Тиран",
    cairoipyramidsdiscovery: "Каир и Египетские пирамиды",
    mountmosesistcatherine: "Гора Моисея и Монастырь",
    bathyscaphesubmarineview: "Подводная лодка Батискаф",
    stcatherinesmonastery: "Монастырь Святой Екатерины",
    coloredcanyonsalama5in1: "Цветной каньон 5 в 1",
    buggysafariicameltrek: "Сафари на багги и верблюды",
    dahabdiscoveryspecial: "Открытие Дахаба",
    cairoipyramidsbyplane: "Каир на самолете",
    supersafaridinnerishow: "Супер сафари с ужином и шоу",
    albatroswaterparkday: "Аквапарк Альбатрос",
    luxorancientruinstrip: "Луксор: Древние руины",
    parasailinghighexperience: "Парасейлинг (Полет на парашюте)",
    petratreasuryjordan: "Петра (Иордания)",
    turkishbathimassage: "Турецкая баня и хаммам",
    dolphinariumfunshow: "Шоу дельфинов",
    swimmingwithdolphins: "Плавание с дельфинами",
  },
  ar: {
    home: "الرئيسية",
    explore: "الرحلات",
    myTrips: "رحلاتي",
    bookNow: "احجز الآن",
    aboutUs: "من نحن",
    contact: "تواصل معنا",
    welcome: "مرحباً بكم في صن رايز تورز",
    makingEveryMoment: "نصنع لحظات لا تُنسى",

    discoveryAwaits: "استكشف سحر الطبيعة",
    exclusive: "حصرية",
    experiences: "تجارب",
    heroDesc: "اكتشف الجواهر الخفية في شرم الشيخ ودهب من خلال رحلاتنا اليومية المختارة بعناية، والمصممة خصيصاً لتناسب عشاق السفر.",
    all: "الكل",
    daily: "رحلات يومية",
    safari: "سفاري",
    seaTrips: "رحلات بحرية",
    priceText: "السعر",
    reviews: "التقييمات",

    ourStory: "قصتنا ورؤيتنا",
    whoWeAre: "من نحن",
    passionateExperts: "خبراء بشغف",
    tailoredExperience: "تجارب مخصصة",
    safetyComfort: "أقصى درجات الأمان والراحة",
    localPresence: "خبرة محلية",
    happyTravelers: "عملاء سعداء",
    safetyRating: "تقييم الأمان",
    egypt: "مصر",
    discoverPassion: "اكتشف الشغف الذي يقف وراء أفضل شركة للرحلات في شرم الشيخ.",
    whoWeAreDesc: "في صن رايز تورز، نؤمن بأن للسفر قوة قادرة على إثراء الحياة. ومنذ انطلاقتنا، كرسنا جهودنا لتقديم تجارب استثنائية، تجمع بين سحر الصحراء وجمال البحر الأحمر برفاهية وأمان لا مثيل لهما.",
    expertsDesc: "يضم فريقنا نخبة من محبي السفر ممن يعرفون كل كنوز سيناء المخفية.",
    tailoredDesc: "نصمم لك رحلات تتناسب تماماً مع ذوقك واحتياجاتك الخاصة.",
    safetyDesc: "سلامتك وراحتك هي دائمًا أولويتنا المطلقة في جميع رحلاتنا.",
    localDesc: "بصفتنا سكاناً محليين، نقدم لك تجربة أصلية لن تجدها في أي مكان آخر.",
    masterpiece: "انطلق في رحلة استثنائية، حيث تمثل كل جولة تحفة فنية بحد ذاتها.",

    myAdventures: "مغامراتي",
    manageBookings: "أدر حجوزاتك واسترجع أفضل لحظاتك بسهولة.",
    appointments: "الحجوزات",
    history: "السجل",
    wishlist: "المفضلة",
    viewDetails: "عرض التفاصيل",
    planNewAdventure: "خطط لمغامرة جديدة",
    explorePremium: "استكشف أكثر من 24 رحلة سياحية فاخرة",

    footerDesc: "نعيد صياغة مفهوم السفر الفاخر في شرم الشيخ. نقدم لك تجارب لا تُنسى تمزج بين إثارة المغامرة، رفاهية الإقامة، وأصالة التراث المحلي.",
    navigation: "روابط سريعة",
    exploreTours: "تصفح الرحلات",
    myBookings: "حجوزاتي",
    support: "الدعم والمساعدة",
    privacyPolicy: "سياسة الخصوصية",
    termsOfService: "شروط الخدمة",
    refundPolicy: "سياسة الاسترداد",
    contactSupport: "التواصل مع الدعم",
    connect: "ابق على تواصل",
    sharmLocation: "شرم الشيخ",
    sinaiEgypt: "جنوب سيناء، مصر",
    supportAvailable: "خدمة العملاء متاحة 24/7",
    allRightsReserved: "جميع الحقوق محفوظة.",

    tourNotFound: "لم يتم العثور على الرحلة",
    tourNotFoundDesc: "عُذراً، ربما تم تغيير مسار المغامرة التي تبحث عنها أو أننا نقوم بتحديثها بميزات أكثر تميزاً.",
    returnToAll: "العودة لقائمة الرحلات",
    experienceOverview: "نبذة عن الرحلة",
    tripItinerary: "برنامج الرحلة",
    whatsIncluded: "الرحلة تشمل",
    notIncluded: "الرحلة لا تشمل",
    essentialPacking: "مستلزمات يفضل إحضارها",
    importantNotes: "ملاحظات هامة",
    priceStartingFrom: "الأسعار تبدأ من",
    adults: "البالغين",
    child: "الأطفال (5-11 سنة)",
    under5: "الأطفال تحت 5 سنوات",
    bookThisExperience: "احجز هذه الرحلة",
    secureCheckout: "دفع آمن • تأكيد فوري للحجز",
    needAssistance: "بحاجة إلى مساعدة؟",
    supportTeamDesc: "خبراء السفر لدينا متاحون على مدار الساعة لمساعدتك في إتمام حجزك.",

    dailytour: "رحلة يومية",
    yachttrip: "رحلة يخت",
    adventure: "مغامرة",
    fullday: "يوم كامل",
    evening: "جولة مسائية",
    diving: "غوص",
    nationalpark: "محمية طبيعية",
    watersports: "رياضات مائية",
    seatrip: "جولة بحرية",
    historical: "تاريخي",
    religious: "ديني",
    sightseeing: "جولة معالم",
    airtour: "جولة جوية",
    entertainment: "ترفيه",
    family: "عائلي",
    wellness: "استجمام وعافية",
    international: "دولي",
    interactive: "تفاعلي",
    
    sharmelshaikhislands: "جزر شرم الشيخ",
    desertparksharm: "محمية سيناء الصحراوية",
    dahabbluehole: "دهب والبلو هول",
    sharmmarinaport: "مارينا شرم الشيخ",
    naambaymarinearea: "منطقة خليج نعمة",
    southsinaireserve: "محمية جنوب سيناء",
    coralreefsanctuary: "محمية الشعاب المرجانية",
    sharmelshaikh: "شرم الشيخ",
    sinai: "سيناء",
    sharm: "شرم",
    dahab: "دهب",
    redsea: "البحر الأحمر",
    reserve: "محمية طبيعية",
    cairo: "القاهرة",
    nuiba: "نويبع",
    jordan: "الأردن",

    hoteltransfer: "انتقالات من وإلى الفندق",
    lunchonyacht: "غداء على متن اليخت",
    softdrinks: "مشروبات غير كحولية",
    professionalguide: "مرشد سياحي محترف",
    snorkelinggear: "معدات الغطس (سنوركلينج)",
    divinggear: "معدات الغوص الكاملة",
    personalexpenses: "المصاريف الشخصية",
    passport: "جواز السفر",
    swimwear: "ملابس السباحة",
    towel: "منشفة البحر",
    sunscreen: "واقي من الشمس",
    bedouintea: "شاي بدوي أصيل",
    quadbike: "دراجات دفع رباعي (بيتش باجي)",
    camelride: "ركوب الجمال",

    "9hours": "9 ساعات",
    "2.5hours": "ساعتان ونصف",
    "1.5hours": "ساعة ونصف",
    "6hours": "6 ساعات",
    "2hours": "ساعتان",
    "5hours": "5 ساعات",
    "24hours": "24 ساعة",
    "17hours": "17 ساعة",
    "11hours": "11 ساعة",
    "10hours": "10 ساعات",
    "7hours": "7 ساعات",
    "4hours": "4 ساعات",
    "3hours": "3 ساعات",

    rasmohammedyachtexperience: "يخت رأس محمد والجزيرة البيضاء",
    quadbikesafariicamelride: "سفاري الدراجات الرباعية وركوب الجمال",
    superdahabdiscovery5in1: "اكتشاف دهب الشامل 5 في 1",
    vippirateshipeveningcruise: "رحلة عشاء VIP مركب القراصنة",
    shoredivingadventure: "مغامرة الغوص من الشاطئ",
    rasmohammednationalpark: "محمية رأس محمد الوطنية",
    divingifunexperience: "تجربة الغوص والرياضات المائية",
    tiranislandyachtexcursion: "رحلة يخت إلى جزيرة تيران",
    cairoipyramidsdiscovery: "اكتشاف القاهرة والأهرامات",
    mountmosesistcatherine: "جبل موسى ودير سانت كاترين",
    bathyscaphesubmarineview: "رؤية بانورامية بالغواصة",
    stcatherinesmonastery: "دير سانت كاترين الأثري",
    coloredcanyonsalama5in1: "الوادي الملون 5 في 1",
    buggysafariicameltrek: "سفاري الباجي وركوب الجمال",
    dahabdiscoveryspecial: "رحلة دهب الخاصة",
    cairoipyramidsbyplane: "القاهرة والأهرامات جواً",
    supersafaridinnerishow: "سوبر سفاري مع عشاء وعرض ترفيهي",
    albatroswaterparkday: "يوم ممتع في أكوا بارك ألباتروس",
    luxorancientruinstrip: "رحلة الأقصر ومعالمها الأثرية",
    parasailinghighexperience: "مغامرة الباراسيلينج (الباراشوت المائي)",
    petratreasuryjordan: "مدينة البتراء الوردية - الأردن",
    turkishbathimassage: "حمام تركي وجلسات تدليك",
    dolphinariumfunshow: "عروض الدلافين الممتعة",
    swimmingwithdolphins: "السباحة مع الدلافين",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");
  const [isMounted, setIsMounted] = useState(false);

  useEffect(() => {
    const savedLang = localStorage.getItem("language") as Language;
    if (savedLang && (savedLang === "en" || savedLang === "ru" || savedLang === "ar")) {
      setLanguage(savedLang);
    }
    setIsMounted(true);
  }, []);

  useEffect(() => {
    if (isMounted) {
      localStorage.setItem("language", language);
      document.documentElement.lang = language;
      document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
    }
  }, [language, isMounted]);

  const t = (key: string) => {
    if (!key) return "";
    const formattedKey = key.toLowerCase().replace(/[\s\W_]+/g, '');
    return (translations[language] as any)[formattedKey] || (translations[language] as any)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
