"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "ru" | "ar";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navbar & Common
    home: "Home",
    explore: "Explore",
    myTrips: "My Trips",
    bookNow: "Book Now",
    aboutUs: "About Us",
    contact: "Contact",
    welcome: "Welcome to Sunrise Tours",
    makingEveryMoment: "MAKING EVERY MOMENT UNFORGETTABLE",

    // Home Page
    discoveryAwaits: "Discovery Awaits",
    exclusive: "Exclusive",
    experiences: "Experiences",
    heroDesc: "Discover the hidden gems of Sharm El-Shaikh and Dahab with our curated daily excursions, designed for the modern traveler.",
    all: "All",
    daily: "Daily",
    safari: "Safari",
    seaTrips: "Sea Trips",
    priceText: "Price",
    reviews: "Reviews",

    // About Page
    ourStory: "Our Story & Vision",
    whoWeAre: "Who We Are",
    passionateExperts: "Passionate Experts",
    tailoredExperience: "Tailored Experience",
    safetyComfort: "Safety & Comfort",
    localPresence: "Local Presence",
    happyTravelers: "Happy Travelers",
    safetyRating: "Safety Rating",
    egypt: "Egypt",
    discoverPassion: "Discover the passion behind Sharm El-Sheikh's premier excursion provider.",
    whoWeAreDesc: "At Sunrise Tours, we believe travel has the power to transform lives. Since our inception, we've dedicated ourselves to providing authentic, safe, and luxurious desert and sea experiences that showcase the true beauty of Egypt's Red Sea coast.",
    expertsDesc: "Our team is made up of avid travelers who know every hidden gem in the Sinai.",
    tailoredDesc: "We provide customized journeys designed to fit your unique travel style and needs.",
    safetyDesc: "Your safety and comfort are our top priorities for every single expedition.",
    localDesc: "Being locals gives us the edge in providing authentic experiences you won't find anywhere else.",
    masterpiece: "Embark on a journey of discovery where every journey is a masterpiece.",

    // Trips Page
    myAdventures: "My Adventures",
    manageBookings: "Manage your bookings and relive your favorite moments.",
    appointments: "Appointments",
    history: "History",
    wishlist: "Wishlist",
    viewDetails: "View Details",
    planNewAdventure: "Plan New Adventure",
    explorePremium: "Explore 24+ premium excursions",

    // Footer
    footerDesc: "Redefining luxury travel in Sharm El-Sheikh. We curate unforgettable experiences that blend adventure, comfort, and local heritage.",
    navigation: "Navigation",
    exploreTours: "Explore Tours",
    myBookings: "My Bookings",
    support: "Support",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    refundPolicy: "Refund Policy",
    contactSupport: "Contact Support",
    connect: "Connect",
    sharmLocation: "Sharm El-Sheikh",
    sinaiEgypt: "South Sinai, Egypt",
    supportAvailable: "24/7 Support Available",
    allRightsReserved: "ALL RIGHTS RESERVED.",

    // Tour Detail Page
    tourNotFound: "Tour Not Found",
    tourNotFoundDesc: "The adventure you're looking for might have been moved or is currently being updated with new premium features.",
    returnToAll: "Return to All Tours",
    experienceOverview: "Experience Overview",
    tripItinerary: "Trip Itinerary",
    whatsIncluded: "What's Included",
    notIncluded: "Not Included",
    essentialPacking: "Essential Packing",
    importantNotes: "Important Notes",
    priceStartingFrom: "Price Starting From",
    adults: "Adults",
    child: "Child (5-11y)",
    under5: "Under 5 Years",
    bookThisExperience: "Book This Experience",
    secureCheckout: "Secure checkout • Instant Confirmation",
    needAssistance: "Need Assistance?",
    supportTeamDesc: "Our travel experts are available 24/7 to help with your booking.",

    // Categories & Locations
    dailytour: "Daily Tour",
    yachttrip: "Yacht Trip",
    adventure: "Adventure",
    fullday: "Full Day",
    evening: "Evening",
    diving: "Diving",
    nationalpark: "National Park",
    watersports: "Water Sports",
    seatrip: "Sea Trip",
    historical: "Historical",
    religious: "Religious",
    sightseeing: "Sightseeing",
    airtour: "Air Tour",
    entertainment: "Entertainment",
    family: "Family",
    wellness: "Wellness",
    international: "International",
    interactive: "Interactive",
    
    sharmelshaikhislands: "Sharm El Sheikh Islands",
    desertparksharm: "Desert Park, Sharm",
    dahabbluehole: "Dahab & Blue Hole",
    sharmmarinaport: "Sharm Marina Port",
    naambaymarinearea: "Naama Bay Marine Area",
    southsinaireserve: "South Sinai Reserve",
    coralreefsanctuary: "Coral Reef Sanctuary",
    sharmelshaikh: "Sharm El Sheikh",
    sinai: "Sinai",
    sharm: "Sharm",
    dahab: "Dahab",
    redsea: "Red Sea",
    reserve: "National Reserve",
    cairo: "Cairo",
    nuiba: "Nuiba",
    jordan: "Jordan",

    // Common Items
    hoteltransfer: "Hotel Transfer",
    lunchonyacht: "Lunch on Yacht",
    softdrinks: "Soft Drinks",
    professionalguide: "Professional Guide",
    snorkelinggear: "Snorkeling Gear",
    divinggear: "Diving Gear",
    personalexpenses: "Personal Expenses",
    passport: "Passport",
    swimwear: "Swimwear",
    towel: "Towel",
    sunscreen: "Sunscreen",
    bedouintea: "Bedouin Tea",
    quadbike: "Quad Bike",
    camelride: "Camel Ride",

    // Durations
    "9hours": "9 Hours",
    "2.5hours": "2.5 Hours",
    "1.5hours": "1.5 Hours",
    "6hours": "6 Hours",
    "2hours": "2 Hours",
    "5hours": "5 Hours",
    "24hours": "24 Hours",
    "17hours": "17 Hours",
    "11hours": "11 Hours",
    "10hours": "10 Hours",
    "7hours": "7 Hours",
    "4hours": "4 Hours",
    "3hours": "3 Hours",

    // Common Tour Titles
    rasmohammedyachtexperience: "Ras Mohammed Yacht Experience",
    quadbikesafariicamelride: "Quad Bike Safari & Camel Ride",
    superdahabdiscovery5in1: "Super Dahab Discovery 5-in-1",
    vippirateshipeveningcruise: "VIP Pirate Ship Evening Cruise",
    shoredivingadventure: "Shore Diving Adventure",
    rasmohammednationalpark: "Ras Mohammed National Park",
    divingifunexperience: "Diving & Fun Experience",
    tiranislandyachtexcursion: "Tiran Island Yacht Excursion",
    cairoipyramidsdiscovery: "Cairo & Pyramids Discovery",
    mountmosesistcatherine: "Mount Moses & St. Catherine",
    bathyscaphesubmarineview: "Bathyscaphe Submarine View",
    stcatherinesmonastery: "St. Catherine's Monastery",
    coloredcanyonsalama5in1: "Colored Canyon Salama 5-in-1",
    buggysafariicameltrek: "Buggy Safari & Camel Trek",
    dahabdiscoveryspecial: "Dahab Discovery Special",
    cairoipyramidsbyplane: "Cairo & Pyramids by Plane",
    supersafaridinnerishow: "Super Safari Dinner & Show",
    albatroswaterparkday: "Albatross Waterpark Day",
    luxorancientruinstrip: "Luxor Ancient Ruins Trip",
    parasailinghighexperience: "Parasailing High Experience",
    petratreasuryjordan: "Petra Treasury - Jordan",
    turkishbathimassage: "Turkish Bath & Massage",
    dolphinariumfunshow: "Dolphinarium Fun Show",
    swimmingwithdolphins: "Swimming with Dolphins",
  },
  ru: {
    home: "Главная",
    explore: "Экскурсии",
    myTrips: "Мои поездки",
    bookNow: "Забронировать",
    aboutUs: "О компании",
    contact: "Контакты",
    welcome: "Добро пожаловать в Sunrise Tours",
    makingEveryMoment: "МЫ СОЗДАЕМ НЕЗАБЫВАЕМЫЕ МОМЕНТЫ",

    discoveryAwaits: "Откройте для себя Египет",
    exclusive: "Эксклюзивные",
    experiences: "Впечатления",
    heroDesc: "Откройте для себя скрытые жемчужины Шарм-эш-Шейха и Дахаба с нашими тщательно отобранными авторскими экскурсиями.",
    all: "Все",
    daily: "Ежедневные",
    safari: "Сафари",
    seaTrips: "Морские прогулки",
    priceText: "Стоимость",
    reviews: "Отзывы",

    ourStory: "Наша история и видение",
    whoWeAre: "О нас",
    passionateExperts: "Влюбленные в свое дело эксперты",
    tailoredExperience: "Индивидуальный подход",
    safetyComfort: "Безопасность и комфорт",
    localPresence: "Знание региона",
    happyTravelers: "Довольных туристов",
    safetyRating: "Рейтинг безопасности",
    egypt: "Египет",
    discoverPassion: "Откройте для себя лучшее туристическое агентство Шарм-эш-Шейха.",
    whoWeAreDesc: "В Sunrise Tours мы верим, что путешествия способны менять жизнь. С самого основания мы посвятили себя созданию аутентичных, безопасных и роскошных туров по пустыне и морю.",
    expertsDesc: "Наша команда — это заядлые путешественники, знающие каждый потаенный уголок Синая.",
    tailoredDesc: "Мы предлагаем персонализированные маршруты, адаптированные под ваши вкусы и пожелания.",
    safetyDesc: "Ваша безопасность и непревзойденный комфорт — наши главные приоритеты.",
    localDesc: "Идеальное знание региона позволяет нам предлагать уникальные маршруты, которых вы не найдете у других.",
    masterpiece: "Отправьтесь в путешествие, где каждая поездка — настоящее произведение искусства.",

    myAdventures: "Мои путешествия",
    manageBookings: "Управляйте бронированиями и вспоминайте лучшие моменты.",
    appointments: "Бронирования",
    history: "История",
    wishlist: "Избранное",
    viewDetails: "Подробнее",
    planNewAdventure: "Новое приключение",
    explorePremium: "Более 24 премиальных экскурсий",

    footerDesc: "Новый взгляд на роскошные путешествия в Шарм-эш-Шейхе. Мы создаем незабываемые впечатления, сочетая приключения, комфорт и местный колорит.",
    navigation: "Меню",
    exploreTours: "Каталог туров",
    myBookings: "Мои бронирования",
    support: "Помощь",
    privacyPolicy: "Политика конфиденциальности",
    termsOfService: "Пользовательское соглашение",
    refundPolicy: "Условия возврата",
    contactSupport: "Служба поддержки",
    connect: "Связь с нами",
    sharmLocation: "Шарм-эш-Шейх",
    sinaiEgypt: "Южный Синай, Египет",
    supportAvailable: "Поддержка 24/7",
    allRightsReserved: "ВСЕ ПРАВА ЗАЩИЩЕНЫ.",

    tourNotFound: "Тур не найден",
    tourNotFoundDesc: "Возможно, данная экскурсия была перемещена или мы обновляем информацию о ней.",
    returnToAll: "Вернуться ко всем турам",
    experienceOverview: "Описание экскурсии",
    tripItinerary: "Программа поездки",
    whatsIncluded: "Что включено",
    notIncluded: "Не включено",
    essentialPacking: "Что взять с собой",
    importantNotes: "Важные примечания",
    priceStartingFrom: "Стоимость от",
    adults: "Взрослые",
    child: "Дети (5-11 лет)",
    under5: "До 5 лет",
    bookThisExperience: "Забронировать экскурсию",
    secureCheckout: "Безопасное бронирование • Мгновенное подтверждение",
    needAssistance: "Нужна помощь?",
    supportTeamDesc: "Наши специалисты готовы помочь вам с бронированием 24/7.",

    dailytour: "Ежедневный тур",
    yachttrip: "Морская прогулка",
    adventure: "Приключение",
    fullday: "На весь день",
    evening: "Вечерний тур",
    diving: "Дайвинг",
    nationalpark: "Национальный парк",
    watersports: "Водный спорт",
    seatrip: "Морская экскурсия",
    historical: "Исторический тур",
    religious: "Паломничество",
    sightseeing: "Обзорная экскурсия",
    airtour: "Авиатур",
    entertainment: "Развлечения",
    family: "Для всей семьи",
    wellness: "Спа и релакс",
    international: "Зарубежный тур",
    interactive: "Интерактивный тур",
    
    sharmelshaikhislands: "Острова Шарм-эш-Шейха",
    desertparksharm: "Пустыня Шарм-эш-Шейха",
    dahabbluehole: "Дахаб и Блу-Хоул",
    sharmmarinaport: "Порт Марина, Шарм",
    naambaymarinearea: "Бухта Наама-Бей",
    southsinaireserve: "Заповедник Южного Синая",
    coralreefsanctuary: "Коралловый заповедник",
    sharmelshaikh: "Шарм-эш-Шейх",
    sinai: "Синай",
    sharm: "Шарм",
    dahab: "Дахаб",
    redsea: "Красное море",
    reserve: "Заповедник",
    cairo: "Каир",
    nuiba: "Нувейба",
    jordan: "Иордания",

    hoteltransfer: "Трансфер туда и обратно",
    lunchonyacht: "Обед на яхте",
    softdrinks: "Безалкогольные напитки",
    professionalguide: "Профессиональный гид",
    snorkelinggear: "Маска и ласты",
    divinggear: "Снаряжение для дайвинга",
    personalexpenses: "Личные расходы",
    passport: "Паспорт",
    swimwear: "Купальник / Плавки",
    towel: "Полотенце",
    sunscreen: "Солнцезащитный крем",
    bedouintea: "Бедуинский чай",
    quadbike: "Квадроциклы",
    camelride: "Катание на верблюдах",

    "9hours": "9 часов",
    "2.5hours": "2.5 часа",
    "1.5hours": "1.5 часа",
    "6hours": "6 часов",
    "2hours": "2 часа",
    "5hours": "5 часов",
    "24hours": "24 часа",
    "17hours": "17 часов",
    "11hours": "11 часов",
    "10hours": "10 часов",
    "7hours": "7 часов",
    "4hours": "4 часа",
    "3hours": "3 часа",

    rasmohammedyachtexperience: "На яхте в Рас-Мохаммед",
    quadbikesafariicamelride: "Сафари на квадроциклах и верблюды",
    superdahabdiscovery5in1: "Супер Дахаб 5 в 1",
    vippirateshipeveningcruise: "Круиз на Пиратской яхте (VIP)",
    shoredivingadventure: "Дайвинг с берега",
    rasmohammednationalpark: "Национальный парк Рас-Мохаммед",
    divingifunexperience: "Дайвинг и водный спорт",
    tiranislandyachtexcursion: "Круиз к острову Тиран",
    cairoipyramidsdiscovery: "Каир и Египетские пирамиды",
    mountmosesistcatherine: "Гора Моисея и Монастырь",
    bathyscaphesubmarineview: "Подводная лодка Батискаф",
    stcatherinesmonastery: "Монастырь Святой Екатерины",
    coloredcanyonsalama5in1: "Цветной каньон 5 в 1",
    buggysafariicameltrek: "Сафари на багги и верблюды",
    dahabdiscoveryspecial: "Открытие Дахаба",
    cairoipyramidsbyplane: "Каир на самолете",
    supersafaridinnerishow: "Супер сафари с ужином и шоу",
    albatroswaterparkday: "Аквапарк Альбатрос",
    luxorancientruinstrip: "Луксор: Древние руины",
    parasailinghighexperience: "Парасейлинг (Полет на парашюте)",
    petratreasuryjordan: "Петра (Иордания)",
    turkishbathimassage: "Турецкая баня и хаммам",
    dolphinariumfunshow: "Шоу дельфинов",
    swimmingwithdolphins: "Плавание с дельфинами",
  },
  ar: {
    home: "الرئيسية",
    explore: "استكشف الرحلات",
    myTrips: "رحلاتي",
    bookNow: "احجز الآن",
    aboutUs: "من نحن",
    contact: "تواصل معنا",
    welcome: "مرحباً بكم في صن رايز تورز",
    makingEveryMoment: "نصنع لكم لحظات لا تُنسى",

    discoveryAwaits: "اكتشف سحر الطبيعة",
    exclusive: "باقات حصرية",
    experiences: "تجارب استثنائية",
    heroDesc: "اكتشف الجواهر الخفية في شرم الشيخ ودهب من خلال رحلاتنا اليومية المصممة بعناية لتمنحك تجربة سفر فاخرة لا تُضاهى.",
    all: "الكل",
    daily: "يومية",
    safari: "سفاري",
    seaTrips: "رحلات بحرية",
    priceText: "السعر",
    reviews: "التقييمات",

    ourStory: "قصتنا ورؤيتنا",
    whoWeAre: "عن شركتنا",
    passionateExperts: "خبراء بشغف",
    tailoredExperience: "تجارب مصممة خصيصاً لك",
    safetyComfort: "أقصى درجات الأمان والراحة",
    localPresence: "خبرة محلية لا تضاهى",
    happyTravelers: "عملاء سعداء",
    safetyRating: "تقييم الأمان",
    egypt: "مصر",
    discoverPassion: "اكتشف الشغف الذي يجعلنا الخيار الأول للرحلات الفاخرة في شرم الشيخ.",
    whoWeAreDesc: "في صن رايز تورز، نؤمن بأن السفر هو رحلة لإثراء الروح. منذ انطلاقتنا، كرسنا جهودنا لتقديم تجارب سياحية استثنائية تجمع بين سحر صحراء سيناء وروعة البحر الأحمر، في إطار من الرفاهية والأمان المطلق.",
    expertsDesc: "يضم فريقنا نخبة من محبي السفر الذين يعرفون أدق أسرار وكنوز سيناء المخفية.",
    tailoredDesc: "نصمم لك رحلات مميزة تتناسب تماماً مع ذوقك الرفيع واحتياجاتك الخاصة.",
    safetyDesc: "نضع سلامتك وراحتك على رأس أولوياتنا في كل تفاصيل رحلتك.",
    localDesc: "بصفتنا خبراء محليين، نضمن لك تجربة أصيلة وحصرية لن تجدها في أي مكان آخر.",
    masterpiece: "انطلق معنا في رحلة استثنائية، حيث كل لحظة هي تحفة فنية بحد ذاتها.",

    myAdventures: "مغامراتي",
    manageBookings: "أدر حجوزاتك بسهولة واسترجع ذكرياتك المفضلة.",
    appointments: "مواعيد الحجوزات",
    history: "سجل الرحلات",
    wishlist: "المفضلة",
    viewDetails: "عرض التفاصيل",
    planNewAdventure: "خطط لمغامرة جديدة",
    explorePremium: "استكشف أكثر من 24 رحلة سياحية فاخرة",

    footerDesc: "نعيد صياغة مفهوم السفر الفاخر في شرم الشيخ. نقدم لك تجارب لا تُنسى تمزج بين إثارة المغامرة، رفاهية الإقامة، وعبق التراث المحلي.",
    navigation: "خريطة الموقع",
    exploreTours: "تصفح باقاتنا",
    myBookings: "حجوزاتي",
    support: "الدعم والمساعدة",
    privacyPolicy: "سياسة الخصوصية",
    termsOfService: "شروط الاستخدام",
    refundPolicy: "سياسة الاسترداد",
    contactSupport: "تواصل مع الدعم",
    connect: "ابقَ على تواصل",
    sharmLocation: "شرم الشيخ",
    sinaiEgypt: "جنوب سيناء، مصر",
    supportAvailable: "خدمة عملاء على مدار الساعة",
    allRightsReserved: "جميع الحقوق محفوظة.",

    tourNotFound: "لم يتم العثور على الرحلة",
    tourNotFoundDesc: "عُذراً، ربما تم تعديل مسار المغامرة التي تبحث عنها، أو أننا نطورها حالياً لتشمل ميزات أكثر رفاهية.",
    returnToAll: "العودة لقائمة الرحلات",
    experienceOverview: "نظرة عامة على التجربة",
    tripItinerary: "برنامج الرحلة",
    whatsIncluded: "ما تشمله الرحلة",
    notIncluded: "الرحلة لا تشمل",
    essentialPacking: "مستلزمات نوصي بإحضارها",
    importantNotes: "ملاحظات هامة",
    priceStartingFrom: "تبدأ الأسعار من",
    adults: "البالغين",
    child: "الأطفال (5-11 سنة)",
    under5: "الأطفال (تحت 5 سنوات)",
    bookThisExperience: "احجز هذه التجربة الحصرية",
    secureCheckout: "دفع آمن • تأكيد فوري للحجز",
    needAssistance: "هل تبحث عن مساعدة؟",
    supportTeamDesc: "نخبة من خبراء السفر لدينا جاهزون لمساعدتك في إتمام حجزك بأي وقت.",

    dailytour: "رحلة يومية",
    yachttrip: "رحلة بحرية فاخرة",
    adventure: "مغامرات شيقة",
    fullday: "جولة ليوم كامل",
    evening: "أمسية ساحرة",
    diving: "تجربة الغوص",
    nationalpark: "محمية طبيعية",
    watersports: "رياضات مائية",
    seatrip: "نزهة بحرية",
    historical: "استكشاف التاريخ",
    religious: "رحلة روحانية",
    sightseeing: "جولة معالم المدينة",
    airtour: "جولة جوية",
    entertainment: "عروض ترفيهية",
    family: "تجارب عائلية",
    wellness: "استجمام وعافية",
    international: "رحلات دولية",
    interactive: "تجارب تفاعلية",
    
    sharmelshaikhislands: "جزر شرم الشيخ الساحرة",
    desertparksharm: "منتزه سيناء الصحراوي",
    dahabbluehole: "دهب والبلو هول",
    sharmmarinaport: "مارينا شرم الشيخ",
    naambaymarinearea: "محمية خليج نعمة",
    southsinaireserve: "محمية جنوب سيناء الطبيعية",
    coralreefsanctuary: "محمية الشعاب المرجانية",
    sharmelshaikh: "شرم الشيخ",
    sinai: "سيناء",
    sharm: "شرم",
    dahab: "دهب",
    redsea: "البحر الأحمر",
    reserve: "محمية طبيعية",
    cairo: "القاهرة",
    nuiba: "نويبع",
    jordan: "الأردن",

    hoteltransfer: "انتقالات فندقية مريحة",
    lunchonyacht: "غداء فاخر على اليخت",
    softdrinks: "مشروبات منعشة",
    professionalguide: "مرشد سياحي خبير",
    snorkelinggear: "معدات الغطس السطحي",
    divinggear: "معدات غوص احترافية",
    personalexpenses: "نفقات شخصية",
    passport: "جواز السفر",
    swimwear: "ملابس السباحة",
    towel: "منشفة",
    sunscreen: "كريم واقي من الشمس",
    bedouintea: "شاي بدوي أصيل",
    quadbike: "دراجات الدفع الرباعي",
    camelride: "تجربة ركوب الجمال",

    "9hours": "9 ساعات",
    "2.5hours": "ساعتان ونصف",
    "1.5hours": "ساعة ونصف",
    "6hours": "6 ساعات",
    "2hours": "ساعتان",
    "5hours": "5 ساعات",
    "24hours": "24 ساعة",
    "17hours": "17 ساعة",
    "11hours": "11 ساعة",
    "10hours": "10 ساعات",
    "7hours": "7 ساعات",
    "4hours": "4 ساعات",
    "3hours": "3 ساعات",

    rasmohammedyachtexperience: "رحلة اليخت الفاخر إلى رأس محمد والجزيرة البيضاء",
    quadbikesafariicamelride: "سفاري الدراجات الرباعية وتجربة الجمال",
    superdahabdiscovery5in1: "اكتشاف دهب سوبر الشامل (5 في 1)",
    vippirateshipeveningcruise: "أمسية كبار الشخصيات على مركب القراصنة",
    shoredivingadventure: "مغامرة الغوص الاحترافي من الشاطئ",
    rasmohammednationalpark: "استكشاف محمية رأس محمد الوطنية",
    divingifunexperience: "تجربة الغوص والرياضات المائية الممتعة",
    tiranislandyachtexcursion: "رحلة اليخت المذهلة إلى جزيرة تيران",
    cairoipyramidsdiscovery: "اكتشاف سحر القاهرة وأهرامات الجيزة",
    mountmosesistcatherine: "رحلة روحانية إلى جبل موسى ودير سانت كاترين",
    bathyscaphesubmarineview: "رؤية بانورامية للأعماق بغواصة باتيسكاف",
    stcatherinesmonastery: "أسرار دير سانت كاترين الأثري",
    coloredcanyonsalama5in1: "مغامرة الوادي الملون (5 في 1)",
    buggysafariicameltrek: "سفاري الباجي وجولة الجمال الصحراوية",
    dahabdiscoveryspecial: "جولة دهب الخاصة والبلو هول",
    cairoipyramidsbyplane: "جولة القاهرة والأهرامات السريعة جواً",
    supersafaridinnerishow: "سوبر سفاري، عشاء بدوي فاخر وعروض ترفيهية",
    albatroswaterparkday: "يوم ممتع في أكوا بارك ألباتروس",
    luxorancientruinstrip: "اكتشاف معالم الأقصر وآثارها الخالدة",
    parasailinghighexperience: "مغامرة التحليق - الباراسيلينج المائي",
    petratreasuryjordan: "رحلة عبر التاريخ إلى مدينة البتراء الوردية (الأردن)",
    turkishbathimassage: "جلسة استرخاء متكاملة في الحمام التركي",
    dolphinariumfunshow: "عروض الدلافين المذهلة لجميع أفراد العائلة",
    swimmingwithdolphins: "تجربة السباحة التفاعلية مع الدلافين",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");
  const [isMounted, setIsMounted] = useState(false);

  useEffect(() => {
    const savedLang = localStorage.getItem("language") as Language;
    if (savedLang && (savedLang === "en" || savedLang === "ru" || savedLang === "ar")) {
      setLanguage(savedLang);
    }
    setIsMounted(true);
  }, []);

  useEffect(() => {
    if (isMounted) {
      localStorage.setItem("language", language);
      document.documentElement.lang = language;
      document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
    }
  }, [language, isMounted]);

  const t = (key: string) => {
    if (!key) return "";
    const formattedKey = key.toLowerCase().replace(/[\s\W_]+/g, '');
    return (translations[language] as any)[formattedKey] || (translations[language] as any)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
